### ISSUE TITLE
webservice não funciona

### ISSUE THREAD

**Issue by aleprovencio** [staticdev/django-cep#6]
Tudo jóia @staticdev ?
Reparei que o webservice não está funcionando, então criei o PR https://github.com/staticdev/django-cep/pull/5 para sua aprovação.

**Comment by staticdev** [comment]
@aleprovencio  fiz o merge da pull request. Vou atualizar no PyPi. Vou criar um issue para testes em seguida e integracao com o TravisCi. Muito obrigado!
