### ISSUE TITLE
Too small package to have dependencies

### ISSUE THREAD

**Issue by staticdev** [staticdev/django-cep#8]
Merge pycorreios used function to this package

**Comment by staticdev** [comment]
@aleprovencio pode me ajudar a remover a dependência da sua pull request? Fiz o merge para corrigir o problema, mas não justifica depender desse pacote a mais. Fora que para suportar o Python 3, o pycorreios precisaria suportar também.

**Comment by aleprovencio** [comment]
@staticdev, concordo com o que está dizendo mas também acredito que o pycorreios seja um bom projeto para investir e além do mais tenta resolver um domínio de requisitos no qual o django-cep toca. Será que te ajudaria igualmente se muito em breve ajudasse a portar o pycorreios para Python 3?

**Comment by staticdev** [comment]
@aleprovencio acho que sim, daria pra ver depois disso se o build com Python 3 ainda roda. Mas penso em importar essa classe Correios que estamos chamando para cá, para evitar a instalação de 2 pacotes mesmo.

**Comment by aleprovencio** [comment]
Ah seria bem interessante agregar mais funcionalidades neste sentido ao django-cep. Uma que acho bem bacana é fazer um preview de custo de frete baseado em AJAX, nos moldes do que você faz com o endereço. Você quer que eu faça um novo PR com o código usado no pycorreios aqui?

**Comment by staticdev** [comment]
@aleprovencio se puder já adianta minha vida =)

**Comment by aleprovencio** [comment]
Feito https://github.com/staticdev/django-cep/pull/10

**Comment by staticdev** [comment]
Vlw @aleprovencio! Fiz o merge e já vou subir para o PyPi a versão 1.1.2.
